sudo: false

os:
  - linux

compiler:
  - gcc

language:
  - cpp

services:
  - docker

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull dcbaker/mesa-demosci ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo FROM dcbaker/mesa-demosci > Dockerfile ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo ADD . /root >> Dockerfile ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t withgit . ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run withgit /bin/sh -c "cd /root && TRAVIS=true CC=$CC CXX=$CXX COMMIT=$TRAVIS_COMMIT ./mesademos-run-tests.sh" ; fi
